[project]
name = "genaiwork"
version = "0.1.0"
description = ""
authors = [
    {name = "Prasanth Reddy"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy (==2.2.0)",
    "pandas (==2.2.2)",
    "streamlit (==1.50.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
